<blockquote class="twitter-tweet">
<p dir="ltr" lang="und"><a href="https://twitter.com/hashtag/helloworld?src=hash">#helloworld</a> <a href="https://twitter.com/hashtag/pdxscience?src=hash">#pdxscience</a> <a href="https://twitter.com/hashtag/internetofbuckets?src=hash">#internetofbuckets</a> <a href="https://t.co/HhEd9jV1hP">pic.twitter.com/HhEd9jV1hP</a></p>
— daniellecrobinson (@daniellecrobins) <a href="https://twitter.com/daniellecrobins/status/784859315030982656">October 8, 2016</a></blockquote>
I’m a PhD candidate (now with a defense date!) in <a href="http://www.ohsu.edu/xd/education/schools/school-of-medicine/academic-programs/neuroscience-graduate-program/">Neuroscience at Oregon Health and Science University</a> in Portland, OR, USA. My research focuses on the insulation of the nervous system. I study Schwann cells. These specialized cells produce a many-layered membrane called myelin that protects and electrically insulates neurons. There is a lot we do not understand about how Schwann cells to make and sustain myelin in a healthy system and about how these cells are affected in diseases. In short, I study one of the smallest units of the nervous system: the cell. Most of the data that I collects is small to medium sized data from cell culture experiments.

In my field, we don’t need to use open tools or programming languages to process, analyze, or visualize our data. My data is very manageable in proprietary software like Excel and Prism. Because we don’t need specialized analysis tools – and because we are busy scientists – it’s easy to keep plugging away with Excel and its friends. The energy barrier to learning new tools is significant, but the rewards to learning open tools are also significant. R and Rmarkdown, (as well as Python and iPython notebook, Github and OSF), enable better data management at the level of the individual researcher and the lab. This eases personnel transitions and eliminates lost data due to dead file formats or poor documentation. It helps you-of-5-years-ago to be a great collaborator for the you-of-today. While cell biologists like myself may not need to use R to get our work done, our workflows would benefit from adopting open tools. <strong>One goal of my fellowship is to work on basic digital literacy education for scientists (particularly wet-lab and small-data scientists), and build cases that illustrate the value of investing time into learning open tools and sharing data.</strong>

Throughout my PhD, I’ve been involved in policy discussions about current scientific climate. I’ve started clubs and served on committees that have tackled graduate training, funding policy, institutional intellectual policy and data policy, as well as national and local policy mechanisms. My work on issues in graduate training showed me how institutional policy changes can have immediate effects on how scientists work, the experience of trainees, and the culture of an institution. <strong>Institutional policies are powerful.</strong> However, they can be slow to change – I’m looking at you, exploratory sub-committee tasked with preparing a report over the next six months and reporting back to the grad council and then the faculty senate! Because science changes faster than governmental or institutional data policies do, many institutions policies (often under the umbrella of Intellectual Property) made sense 15 years ago, but are now not relevant to today’s collaboration, data sharing, and open source software development methods.  Another major goal of my fellowship is to work on understanding the current landscape of institutional policies that apply to data and software. <strong>I want to develop tools to help scientists communicate effectively with administration, faculty, and Intellectual Property offices</strong> to advocate for policies that facilitate scientific discovery and collaboration.

I’d also like to continue to build community across different scientific disciplines and between scientists and the open source community. Like with this <a href="https://twitter.com/science_hackPDX/status/784907702866546689">LaCroix delivery drone</a> and <a href="https://twitter.com/science_hackPDX/status/784805707606429697">this potato interface</a>.

<a href="https://mozscienceblog.wpengine.com/wp-content/uploads/2016/10/PI_Scope_CuRhPM-VUAAEmau.jpg"><img class="size-medium wp-image-3797 aligncenter" src="https://mozscienceblog.wpengine.com/wp-content/uploads/2016/10/PI_Scope_CuRhPM-VUAAEmau-300x225.jpg" sizes="(max-width: 300px) 100vw, 300px" srcset="https://mozscienceblog.wpengine.com/wp-content/uploads/2016/10/PI_Scope_CuRhPM-VUAAEmau-300x225.jpg 300w, https://mozscienceblog.wpengine.com/wp-content/uploads/2016/10/PI_Scope_CuRhPM-VUAAEmau-768x576.jpg 768w, https://mozscienceblog.wpengine.com/wp-content/uploads/2016/10/PI_Scope_CuRhPM-VUAAEmau-1024x768.jpg 1024w, https://mozscienceblog.wpengine.com/wp-content/uploads/2016/10/PI_Scope_CuRhPM-VUAAEmau.jpg 1200w" alt="pi_scope_curhpm-vuaaemau" width="300" height="225" /></a><a href="https://mozscienceblog.wpengine.com/wp-content/uploads/2016/10/crispr_SHD_CubbszWVIAE8ZA_.jpg_large.jpg"><img class="size-medium wp-image-3799 aligncenter" src="https://mozscienceblog.wpengine.com/wp-content/uploads/2016/10/crispr_SHD_CubbszWVIAE8ZA_.jpg_large-300x300.jpg" sizes="(max-width: 300px) 100vw, 300px" srcset="https://mozscienceblog.wpengine.com/wp-content/uploads/2016/10/crispr_SHD_CubbszWVIAE8ZA_.jpg_large-300x300.jpg 300w, https://mozscienceblog.wpengine.com/wp-content/uploads/2016/10/crispr_SHD_CubbszWVIAE8ZA_.jpg_large-150x150.jpg 150w, https://mozscienceblog.wpengine.com/wp-content/uploads/2016/10/crispr_SHD_CubbszWVIAE8ZA_.jpg_large-768x768.jpg 768w, https://mozscienceblog.wpengine.com/wp-content/uploads/2016/10/crispr_SHD_CubbszWVIAE8ZA_.jpg_large-1024x1024.jpg 1024w" alt="_crispr_shd_cubbszwviae8za_-jpg_large" width="300" height="300" /></a><a href="http://www.the-odin.com/all-products/">CRISPR’d E. coli</a> viewed with a 3D printed Raspberry PI controlled microscope (<a href="https://twitter.com/jenny_molloy">by Jenny Molloy</a>) at <a href="http://portland.sciencehackday.org/">Science Hack Day PDX</a>
