<a href="http://www.daniellecrobinson.com/wp-content/uploads/2017/01/board-room.jpg"><img class="size-medium wp-image-88 aligncenter" src="http://www.daniellecrobinson.com/wp-content/uploads/2017/01/board-room-300x121.jpg" alt="board-room" width="300" height="121" /></a>

Collaborating on events with my local (Portland, OR, USA) tech community has been a really enjoyable part of my PhD training. Though this community work does not directly relate to my cell biology PhD research, it has helped me develop skills that have helped me succeed in (and out of) the lab environment.  Building a local network of friends in colleagues in technical fields has helped me in so many ways. Perhaps most critically, I've met great people!

For three weeks this Fall, I collaborated with<span class="gmail-Apple-converted-space"> </span><a href="https://twitter.com/lilscientista">Lilly Winfree</a> (PhD in Neuroscience at OHSU, Women in Science PDX) and<span class="gmail-Apple-converted-space"> </span><a href="https://twitter.com/shae_wat">Shaelyn Watson</a> (Software Engineer at Civil Comments, Women Who Code PDX, and ChickTech PDX) to host a negotiation and career development workshop for women and underrepresented people in science, technology, engineering, and mathematics (STEM) fields with career coach<span class="gmail-Apple-converted-space"> </span><a href="https://twitter.com/JessicaJoEllen">Jessica Williams</a>. This workshop series brought 40-60 ecologists, cyber security experts, data scientists, neuroscientists, software developers, project managers, actuaries, postdocs, PhD candidates, bioinformatitans, and other technical professional together in a welcoming environment to talk about our careers.  Personally, it was valuable to hear the perspectives from the people in the other fields. Often, we dealt with very similar issues.

Of course, I meant to write this up earlier, but reflecting on professional and life goals is a December past-time of mine. In that spirit, I offer up a summary of this negotiation and professional development workshop as another tool for personal strategic planning this winter!

Each week, at least one of Jessica's points really resonated with me, and I'll expand upon one point from each session below.

<strong>Week 1: Negotiation and baggage</strong>

Rather than offering a set of negotiation tools, Jessica encouraged participants to examine their own motivations and baggage that they might bring to a negotiation (or really, any conversation). Her advice was that each person should do the personal work necessary to really understand their own goals.  What does this mean? Well, rather than giving us boiler plate advice, like "anchor high", Jessica encouraged us to figure out what we need to feel valued. If you understand your needs and limitations, it's easier to advocate for your interests and avoid being swept up in a conversation. Part of understanding your goals in a negotiation is researching salary and benefits of similar positions, and speaking to people in that industry. But part of it is also personal emotional work. For example, do you walk into a negotiation expecting the worst? Why? Maybe you had a manipulative boss five years ago, or you got turned down for a raise once and are still spooked. Spending a little time on self reflection can help you understand what baggage you may be bringing to the negotiation. Once you identify it, leave the baggage at home.

<strong>Once you understand yourself a little better, you can map out what you need to feel valued.</strong> Sometimes it's money, if so - how much? Sometimes it's flexibility or vacation time. Sometimes it's conferences or other chances for professional growth. Of course, sometimes it's a job. When you just need a job, you can deal with a pay cut if the work environment is healthy and there is room for growth.

Now, you've identified your baggage and figured out what you want from this negotiation. What's next?

The next step is important and provoked much debate among our STEM-field attendees. Jessica advised us that if you are asked to give a salary range, you kindly decline and allow them to tell you what they have in mind. This part of the session had lots of hands in the air with specific situations where people had been asked to give a salary range and Jessica gave great sample language for each situation. There are many ways to politely decline! Jessica convincingly advised us to never say a salary number first. Because you are your own advocate in a negotiation, you need the  information about how much your potential new employer values you. If you say the first number, you don't get that information. Also, women tend to sell themselves short.

If you enter a negotiation knowing your needs and your value and are offered a salary/benefit package that doesn't meet your needs -  you will be in a stronger place to counter with a number that does or walk away.  If you are offered a salary/benefit package that does meet your needs... great! You can work with that. And you don't even need to feel bad if you just take the offer - as long as your needs are being met (and again, if having any job is your number one need, ain't no shame - celebrate the offer).  So, examine your baggage and then check those bags! Then let them say the first number.

<strong>Week 2: Boundaries</strong>

The frontline of the life-work balance battle is email. A year ago I started leaving my phone in another room when I went to bed so I wouldn't be able to check my work email before I fell asleep and wind up awake for hours stressing out. Then a few months ago I had to take it to the next level and remove my work email from my phone all together. I have a toddler, and I'd absentmindedly check my work email while I was hanging out with my kid. If there was some stressful email waiting for me, there was nothing I could do about it because I was at the playground/playing trains/on a walk and so I'd just get really stressed out and ruin my time with my kid. I can still check work email through a webapp, but it's more annoying so I don't tend to check it unless I am ready to deal with what lies in the inbox.

The week 2 session showed me that 45/45 people at the session had similar struggles with email. Beyond email, participants raised issues that helped me see a deeper level to boundary setting in my professional life.  It's not just how you organize your time, it's how you approach relationships, commitments, and conversations. Jessica reminded us that when we don't set boundaries in an effort to be accommodating, it is harder for others to work with us because we are inconsistent. This was a mic-drop moment for me. It is inconsistent and unpredictable to have boundaries that are always shifting! It's not actually accommodating! <strong>Clear and consistent boundaries are what make other people feel comfortable</strong>. With clear boundaries, others know what they can expect from us. Clear boundaries prevent you from being overextended. One participant encouraged the room to think of clear boundaries as increased surface area for interaction with others.

I left the session feeling new agency to set boundaries at work that will enable me to be my best professional self.

<strong>Week 3: What can I do for you?</strong>

The final session focused on networking. Unlike other networking primers I've encountered, we spent zero time honing our elevator pitchers or talking about how to get 5 minutes with a big name. Instead, we focused on thinking of networking as a time to learn about others and ask "What can I do for you?"  - importantly, without offering free work. We discussed how to keep interactions short, meaningful, and memorable. Meeting a new person just needs to be an introduction, not a life story. Your goal is to learn a little about that person and consider if you have a contact or other resource to offer. This gives you an easy way to follow up - because you offered to share a link to a workshop, or introduce them to someone you are obligated to follow up. We also talked about reading body language - don't bother approaching groups of two leaning in to talk to each other, go for a group of three with open body language. And, of course, the power of follow up.

One of the most important things I took away from this session was not to force it.  This means you get to go home, guilt-free, if it's not working. Some nights, things are flowing at a networking event. You meet people, you have great conversations, and it feels effortless. Other nights, you have trouble finding your flow or a knot in your stomach. Or you get stuck with one person for half the night. <strong>Don't beat yourself up if an event isn't working for you.</strong> This doesn't mean you are no good at networking events. Don't say "I'm done with networking!" Just call it a night and go home to relax. Later, try to identify what went wrong. Maybe someone asked you a question that made you insecure (for me, this used to be "What do you do?"). Maybe you knew you were not in the mood and tried to push it to go out anyway. Perhaps you can identify a type of interaction or a question that makes you feel insecure, you can practice an answer to that question and slay that dragon next time.  If you got stuck with one person, remember that "two lone wolves mate for life" and approach groups next time. Was the event was big and overwhelming? Next time you can plan to attend for a shorter time, try to meet one person, and follow up for one-on-one informational interview. Or target smaller events or events with a central focus like a talk or a workshop. Networking is work, and not every event will go smoothly. Go easy on yourself and get back out there!

<strong>In closing: </strong>I am inspired to continue bringing people in science together with those who work in other technical fields through my Mozilla fellowship year. This series helped me to identify and resolve some issues that were giving me problems in the lab. Building local community is a critical part of open science advocacy because it gets scientists talking across disciplines and it helps build relationships outside the ivory tower. It felt great to create a safe space to talk about goals, struggles, and what's worked or what isn't working in our professional lives.  <a href="https://twitter.com/JessicaJoEllen">Jessica Williams'</a> workshop style was refreshing, particularly relative to typical academic events, and she really helped everyone open up. Science in academic lab can be isolating - like alone in a dark room for 10 hours isolating.  Building diverse a local community can help you learn technical skills that will help your research (ahem, git and programming), <a href="http://www.tobyfee.com/archives/date/2016/10">meet people who can help your research</a>, meet people you can work on fun projects or future events with, and help you identify the next step in your career. I'm happy to talk to anyone interested in organizing an event like this in their community!

<em>Header image courtesy of <a href="https://www.flickr.com/photos/wocintechchat/with/25900843762/">#WOCinTech Chat Tumblr</a></em>

Cross-posted on <a href="https://science.mozilla.org/blog">science.mozilla.org</a>
